[package]
name = "june_vm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3.2"
dyn-clone = "1.0.5"
hashbrown = "0.12.1"
